#!/usr/bin/env ansible-playbook
- hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    homebrew_packages:
    - asdf
    - eza # ls replacement
    - ffmpeg
    - flyctl
    - fzf
    - git
    - git-lfs
    - jq
    - just
    - kubectx
    - neovim
    - overmind
    - python
    - rg
    - starship
    - stow
    - tmux
    - tmuxinator
    - tree
    - zoxide # cd replacement
    - imagemagick
    - hashicorp/tap/terraform
    - yt-dlp



    homebrew_cask_packages:
    # - 1password
    - alacritty
    - anki
    - calibre
    - docker
    - dropbox
    - raycast
    - firefox
    - font-daddy-time-mono-nerd-font 
    - font-inconsolata-nerd-font
    - font-iosevka-nerd-font
    - font-lora
    - obsidian
    - vlc


    node_versions:
    - 18.9.1

    pyenv_python_versions:
    - 3.10.7

  tasks:
    - import_tasks: tasks/ssh.yml
    - import_tasks: tasks/zsh.yml
    - import_tasks: tasks/homebrew.yml
    - import_tasks: tasks/nvim.yml
    - import_tasks: tasks/node.yml
    # - import_tasks: tasks/python.yml
    - import_tasks: tasks/personal-projects.yml
    - import_tasks: tasks/dotfiles.yml
    - import_tasks: tasks/cron.yml

