- name: Update homebrew
  homebrew:
    name: git
    state: latest
    update_homebrew: true
  tags:
    - homebrew

- name: Tap terraform
  community.general.homebrew_tap:
    name: hashicorp/tap

- name: Install homebrew packages
  homebrew:
    name: '{{ homebrew_packages }}'
    state: latest
  tags:
    - brew

- name: Install homebrew cask packages
  command: brew install {{ homebrew_cask_packages|join(" ") }}
  tags:
    - brew
    - cask
