- name: Clone Obsidian
  ansible.builtin.git:
    repo: 'git@github.com:Jwhiles/obsidian.git'
    bare: false
    dest: "{{ lookup('env', 'HOME') }}/Obsidian/obsidian"
  tags:
    - install
    - personal-project

- name: Clone johncom
  ansible.builtin.git:
    repo: 'git@github.com:Jwhiles/johncom.git'
    bare: false
    dest: "{{ lookup('env', 'HOME') }}/personal/johncom"
  tags:
    - install
    - personal-project

- name: Clone crowland
  ansible.builtin.git:
    repo: 'git@github.com:Jwhiles/crowland.git'
    bare: false
    dest: "{{ lookup('env', 'HOME') }}/personal/crowland"
  tags:
    - install
    - personal-project
