homebrew_packages:
# - autoconf
# - autojump
# - automake
# - awscli
# - cloc
# - coreutils
# - cowsay
# - enchant
# - exiftool
# - fd
# - fdupes
- ffmpeg
# - freetype
# - fswatch
# - gdal
# - gdbm
- git
# - git-delta
# - github/gh/gh
# - goaccess
# - gpg
# - graphicsmagick
# - heroku/brew/heroku
# - hyperfine
# - inetutils
# - jhead
# - jpeg
# - jpegoptim
- jq
# - lesspipe
# - libevent
# - libmemcached
# - libpng
# - libtool
# - libyaml
# - memcached
# - myrepos
- neovim
# - ncdu
# - nginx
- nvm
# - openssl
# - ossp-uuid
# - pandoc
# - parallel
# - percona-toolkit
# - pkg-config
# - postgresql
# - pre-commit
# - pwgen
- pyenv
- python
# - qpdf
# - readline
# - rg
# - rsync
# - rtmpdump
# - sd
# - shellcheck
# - sqlite
- starship
- stow
# - swig
- tmux
- tree
# - watch
# - watchman
# - wget
# - xz
# - zlib
# - zsh-completions

homebrew_cask_packages:
# - anki
- calibre
# - discord
- docker
- firefox
# - homebrew/cask-fonts/font-ubuntu-mono-nerd-font
# - franz
- iterm2
# - istat-menus
# - java
# - karabiner-elements
# - keyboard-maestro
# - mactex
# - mplayerx
- obsidian
# - paintbrush
- rectangle
# - skim
- steam
# - tableplus
# - vagrant
- vlc

pyenv_python_versions:
# In precedence order
- 3.10.7

pip_packages:
- monome-druid

source_key: "./.ssh/id_rsa"
dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"

