homebrew_packages:
- fzf
- ffmpeg
- git
- jq
- neovim
- nvm
- overmind
- pyenv
- python
- rg
- spotifyd
- spotify-tui
- starship
- stow
- tmux
- tmuxinator
- tree
# - watchman

homebrew_cask_packages:
- 1password
- anki
- calibre
- darktable
- docker
- firefox
- homebrew/cask-fonts/font-inconsolata-nerd-font
- homebrew/cask-fonts/font-iosevka-nerd-font
- homebrew/cask-fonts/font-daddy-time-mono-nerd-font 
- iterm2
- obsidian
- rectangle
- steam
- vlc

pyenv_python_versions:
# In precedence order
- 3.10.7

source_key: "./.ssh/id_rsa"
dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"

