- name: cron environment
  cron:
    name: 'env {{ item }}'
    job: ''
    minute: '{{ item }}'
    hour: ''
    day: ''
    weekday: ''
    month: ''
  loop:
  - SHELL=/bin/bash
  - HOME={{ ansible_env.HOME }}
  tags:
  - cronjob

- name: lifelogger download
  cron:
    minute: '5'
    name: Sync Obsidian
    job: $HOME/Obsidian/obsidian/SYNC_OBS
  tags:
  - cronjob

